  services:
    backend:
      build:
        context: ./back-end
      environment:
        - NODE_ENV=${NODE_ENV:-production}
      ports:
        - "5002:5002"
      networks:
        - training-mern-network
      depends_on:
        - mongo


    frontend:
      build:
        context: ./front-end
        args:
          BUILD_ENV: ${NODE_ENV:-production}
      ports:
        - "8002:80"
      networks:
      - training-mern-network # <--- Make sure this is here!

    
    dashboard:
      build:
        context: ./dashboard
      ports:
        - "8003:80"
      networks:
        - training-mern-network


    mongo:
      image: mongo:latest
      environment:
        - GLIBC_TUNABLES=glibc.pthread.rseq=1
      ports:
        - "27019:27017"
      networks:
        - training-mern-network
      
  networks:
    training-mern-network:
      driver: bridge
